site_name: PSFMachine
nav:
    - Home: index.md
    - Machine: machine.md
    - TPFMachine : tpf.md
    - FFIMachine : ffi.md
    - Aperture Photometry : aperture.md
    - SSMAchine : superstamp.md
theme:
  name: "material"
  icon:
      logo: material/star-plus
repo_url: https://github.com/SSDataLab/psfmachine
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - src/my_package
