site_name: PSFMachine
nav:
    - Home: index.md
    - API:
      - Machine: machine.md
      - TPFMachine : tpf.md
      - FFIMachine : ffi.md
      - Aperture Photometry : aperture.md
      - SSMachine : superstamp.md
      - PerturbationMatrix : perturbation.md
      - Utils : utils.md
    - Tutorials:
        - Basic PSFMachine: tutorials/Tutorial_10_TPFs.ipynb
        - TPFMachine: tutorials/Tutorial_11_TPFs.ipynb
        - FFIMachine: tutorials/Tutorial_20_FFI.ipynb
        - Basic SSMachine: tutorials/Tutorial_30_k2ss.ipynb
        - SSMachine: tutorials/Tutorial_31_k2ss.ipynb
theme:
  name: "material"
  icon:
      logo: material/star-plus
repo_url: https://github.com/SSDataLab/psfmachine
plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      include_source: True
      ignore_h1_titles: False
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - src/psfmachine
