site_name: PSFMachine
nav:
    - Home: index.md
    - API:
      - Machine: machine.md
      - TPFMachine : tpf.md
      - FFIMachine : ffi.md
      - Aperture Photometry : aperture.md
      - SSMAchine : superstamp.md
    - Tutorials:
        - FFIMachine : tutorials/Tutorial_2_FFI.ipynb
        - SSMachine : tutorials/Tutorial_3_k2_clusters.ipynb
theme:
  name: "material"
  icon:
      logo: material/star-plus
repo_url: https://github.com/SSDataLab/psfmachine
plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      include_source: True
      ignore_h1_titles: False
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - src/my_package
