name: flake8

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: flake8
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Run flake8
      run: |
        make flake8
